#!/bin/bash -eu
set -o pipefail

script_dir="$(cd "$(dirname "$0")"; pwd)"
root_dir="$(cd "${script_dir}/.."; pwd)"

revision="$(git name-rev HEAD | cut -f 1 -d' ')"


for target in {UIKitTestable,UIKitAssertions,UIKitTestableAppTests}; do
	bundle exec -- jazzy \
		--clean \
		--sdk 'iphone' \
		--author 'Kuniwak' \
		--author_url 'https://github.com/Kuniwak' \
		--github_url 'https://github.com/Kuniwak/UIKitTestable' \
		--github-file-prefix "https://github.com/Kuniwak/UIKitTestable/tree/${revision}" \
		--undocumented-text '' \
		--module-version "${revision}" \
		--min-acl 'internal' \
		--xcodebuild-arguments "-scheme,${target},CODE_SIGNING_ALLOWED=NO" \
		--module "$target" \
		--output "${root_dir}/docs/${target}"
done
