#!/bin/bash -eu
set -o pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.."; pwd)"


(cd "$ROOT_DIR"
	for xcodeproj in {./UIKitTestable/UIKitTestable.xcodeproj,./UIKitAssertions/UIKitAssertions.xcodeproj,./UIKitTestableApp/UIKitTestableApp.xcodeproj}; do
		bundle exec synx "$xcodeproj"
	done
)
